Module Module1
    Public LeftMotorSpeed1 As Single
    Public RightMotorSpeed1 As Single
    Public LeftMotorSpeed2 As Single
    Public RightMotorSpeed2 As Single
    Public LeftMotorActivationWord1 As String
    Public LeftMotorActivationWord2 As String
    Public MotorDeactivationWord As String
    Public RightMotorActivationWord1 As String
    Public RightMotorActivationWord2 As String
    Public A_char As Char
    Public B_char As Char
    Public LB_char As Char
    Public RB_char As Char
    Public X_char As Char
    Public Y_char As Char
    Public LS_char As Char
    Public RS_char As Char
    Public BA_char As Char
    Public ST_char As Char
    Public PU_char As Char
    Public PD_char As Char
    Public PL_char As Char
    Public PR_char As Char
    Public LT1_char As Char
    Public LT2_char As Char
    Public RT1_char As Char
    Public RT2_char As Char
    Public LSX0_char As Char
    Public LSX2_char As Char
    Public LSY0_char As Char
    Public LSY2_char As Char
    Public RSX0_char As Char
    Public RSX2_char As Char
    Public RSY0_char As Char
    Public RSY2_char As Char
End Module
